name: matrix

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Log Node version
        run: node -v
       
      