---
name: "workflow"

'on':
  push:
    branches:
      - main-workflow
    tags:
      - "*"
  pull_request:
    branches:
      - main-workflow

jobs:
  ci:
    name: "CI Integration"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run the tests
        run: yarn test
      
      - name: Build
        run: yarn build

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"